
scoel : scoel.icn scoelgram.icn scoellex.icn errors.icn Nodes.icn semantics.icn dataTypes.icn intermediateCode.icn
	unicon -fs -u scoel.icn scoelgram.icn scoellex.icn errors.icn Nodes.icn semantics.icn dataTypes.icn intermediateCode.icn
	
scoelgram.icn :  scoelgram.y
	iyacc -i scoelgram.y
	